#!/usr/bin/env python3

from functools import cache
from pathlib import Path
import yaml_manifest


configfile: "config/config.yaml"


# setup paths
manifest = yaml_manifest.Manifest.from_yaml(Path(config["manifest"]))


include: "rules/01_functions.smk"
include: "rules/05_globals.smk"
include: "rules/10_assembly_data_downloader.smk"
include: "rules/11_pipeline_result_uploader.smk"
include: "rules/20_pacbio_qc.smk"
include: "rules/21_ont_qc.smk"
include: "rules/25_hic_qc.smk"
include: "rules/30_stage_busco_dataset.smk"
include: "rules/31_stage_fcsgx_db.smk"


rule run_download:
    input:
        manifest.reads.flat_paths("raw"),


rule run_qc:
    input:
        manifest.reads.flat_paths("qc"),


rule stage_busco:
    input:
        expand(rules.expand_busco_lineage_files.output, busco_dataset=busco_dataset),


rule pre_genomeassembly:
    input:
        rules.run_download.input,
        rules.run_qc.input,
        rules.stage_busco.input,


rule post_genomeassembly:
    input:
        rules.stage_busco.input,
        rules.stage_fcsgx.output,
        Path(manifest.get_dir("results"), "upload_receipts", "genomeassembly.jsonl"),


rule target:
    default_target: True
    input:
        rules.run_download.input,
        rules.run_qc.input,
