#!/usr/bin/env python3

rule assembly_data_downloader:
    input:
        config["manifest"]
    output:
        directory("downloads")
    log:
        Path("logs", "assembly_data_downloader.log")
    threads:
        8
    container:
        "docker://quay.io/biocontainers/atol-genome-launcher:0.7.2--pyhdfd78af_0"
    shell:
        "assembly-data-downloader "
        "{input} "
        "2> {log}"