#!/usr/bin/env python3

import yaml_manifest
from pathlib import Path

# setup paths
manifest = yaml_manifest.Manifest.from_yaml(Path(config["manifest"]))


include: "rules/10_assembly_data_downloader.smk"
include: "rules/20_qc.smk"


rule target:
    default_target: True
    input:
        rules.pacbio_qc_target.input,
