dataset_id: "gyRhyGra1"
assembly_version: 2
busco_odb10_dataset_name: "helotiales"
busco_odb12_dataset_name: "helotiales"
hic_motif: "GATC,GANTC,CTNAG,TTAA"
mito_code: 4
mitohifi_reference_species: "Rhynchosporium commune"
oatk_hmm_name: "dikarya_mito"
scientific_name: "Rhynchosporium graminicola"
taxon_id: 2792576
reads:
  PACBIO_SMRT:
    bpa-pp-pacbio-hifi-395385-m84073_230802_055109_s2:
      resources:
        - url: "https://data.bioplatforms.com/dataset/bpa-pp-pacbio-hifi-395385-m84073_23\
            0802_055109_s2/resource/6c3300906111b99872ebc2efcfa946ee/download/3\
            95385_PP_AGRF_m84073_230802_055109_s2.ccs.bam"
          md5sum: "6c3300906111b99872ebc2efcfa946ee"
      base_url: "https://downloads-qcif.bioplatforms.com/bpa/pp_staging/pacbio-hifi/B\
        PAOPS-1452/20230809_PP_AGRF_CAGRF230615297_m84073_230802_055109_s2/"
  # OXFORD_NANOPORE:
  #   bpa-ipm-ont-promethion-606218-pbe32261:
  #     - url: "https://data.bioplatforms.com/dataset/bpa-ipm-ont-promethion-606218-pbe32261/resource/c9d9d5b51706e8fab657471edeb9a185/download/606218_IPM_BRF_PBE32261_ONTPromethION_fastq_pass.tar"
  #       md5sum: "c9d9d5b51706e8fab657471edeb9a185"
  Hi-C:
    bpa-grasslands-hi-c-371565-373565:
      base_url: "https://downloads-qcif.bioplatforms.com/bpa/grasslands/genomics-hi-c\
        /BPAOPS-1514/20231109_AG_BRF_HMMYTDRX3/"
      r1:
        resources:
          - url: "https://data.bioplatforms.com/dataset/bpa-grasslands-hi-c-371565-373565/r\
              esource/5fb1bde2e50768d6b22aa2e00f97352b/download/369564_LibID371\
              565_AG_BRF_HMMYTDRX3_TCAGCATC_S1_L001_R1_001.fastq.gz"
            md5sum: "5fb1bde2e50768d6b22aa2e00f97352b"
            lane_number: "L001"
      r2:
        resources:
          - url: "https://data.bioplatforms.com/dataset/bpa-grasslands-hi-c-371565-373565/r\
              esource/31b685a72a8af749b846ee26f0191eff/download/369564_LibID371\
              565_AG_BRF_HMMYTDRX3_TCAGCATC_S1_L001_R2_001.fastq.gz"
            md5sum: "31b685a72a8af749b846ee26f0191eff"
            lane_number: "L001"
