reads_path:
  - "/scratch/pawsey1132/tharrop/atol-genome-launcher-testing/rSaiEqu1/trimmed_pacbio_reads/350822_AusARG_AGRF_DA080843.ccs.trim.fastq.gz"
  - "/scratch/pawsey1132/tharrop/atol-genome-launcher-testing/rSaiEqu1/trimmed_pacbio_reads/350822_AusARG_AGRF_DA095606.ccs.trim.fastq.gz"
reads_type: "hifi"
reads_layout: "SINGLE"
sample_id: "rSaiEqu1"
scientific_name: "Saiphos equalis"
busco_lineages: "sauropsida_odb10"
taxid: 172942
